#!/bin/bash
# Continuous Integration build script.

echo '========== Set Up RVM ==============================================='
export PATH=$PATH:~/.rvm/bin
source ~/.rvm/scripts/rvm
set -e # Exit on any error
cd .   # Kick off the rvmrc
set -x # Echo each command

echo '========== Verify Environment ======================================='
ruby -v
gem env gemdir
env | sort

echo '========== Install Gems ============================================='
bundle --no-color install

echo '========== Run Specs ================================================'
# Set rspec output options
bundle exec validate
