#!/bin/bash
# Continuous Integration build script.

echo '========== Set Up RVM ==============================================='
export PATH=$PATH:~/.rvm/bin
source ~/.rvm/scripts/rvm
set -e # Exit on any error
cd .   # Kick off the rvmrc
set -x # Echo each command

echo '========== Install Gems ============================================='
bundle --no-color install

echo '========== Verify Backlog ==========================================='
bundle exec validate
